# Generated by Django 4.1.3 on 2022-11-16 01:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0002_jogo_criado_por"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jogo",
            name="criado_por",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jogos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
